version: '3.9'

services:
  # clickhouse:
  #   image: bitnami/clickhouse:25.1.3-debian-12-r1
  #   container_name: gymnote-clickhouse
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=true
  #     - CLICKHOUSE_DB=${DB_NAME}
  #     - CLICKHOUSE_USER=${DB_USER}
  #     - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
  #     - CLICKHOUSE_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - '9000:9000'
  #     - '8123:8123'
  #   volumes:
  #     - clickhouse_data:/var/lib/clickhouse
  #   restart: unless-stopped
  #   logging:
  #     driver: none # for space keeping

  mongo:
    image: mongo:8.0
    hostname: mongo1
    container_name: gymnote-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    logging:
      driver: none # for space keeping

  redis:
    image: redis:8.0-M03-bookworm
    container_name: gymnote-redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    logging:
      driver: none # for space keeping

volumes:
  # clickhouse_data:
  mongo_data:
  redis_data:
