version: '3.9'

services:
  clickhouse:
    image: bitnami/clickhouse:25.1.3-debian-12-r1
    container_name: gymnote-clickhouse
    environment:
      - ALLOW_EMPTY_PASSWORD=true
      - CLICKHOUSE_DB=${DB_NAME}
      - CLICKHOUSE_USER=${DB_USER}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=${DB_PASSWORD}
    ports:
      - '9000:9000'
      - '8123:8123'
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: unless-stopped
    logging:
      driver: none # for space keeping

  clickhouse-backup:
    image: altinity/clickhouse-backup:2.6.5
    container_name: gymnote-clickhouse-backup
    profiles:
      - backup
    environment:
      - LOG_LEVEL=info
      - CLICKHOUSE_HOST=host.docker.internal # hostname - bot
      - CLICKHOUSE_PORT=${DB_PORT}
      - CLICKHOUSE_USERNAME=${DB_USER}
      - CLICKHOUSE_PASSWORD=${DB_PASSWORD}
      - CLICKHOUSE_DEBUG=false
      - REMOTE_STORAGE=s3
      - S3_ACCESS_KEY=${S3_ACCESS_KEY_ID}
      - S3_SECRET_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_FORCE_PATH_STYLE=true
      - S3_ACL=private
    volumes:
      - ./tools/scripts:/scripts
    volumes_from:
      - clickhouse:rw
    restart: no
    command:
      - sh
      - '/scripts/backup.sh'

  redis:
    image: redis:8.0-M03-bookworm
    container_name: gymnote-redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    logging:
      driver: none # for space keeping

volumes:
  clickhouse_data:
  redis_data:
